### ISSUE TITLE
Typed Array Issues on Clean

### ISSUE THREAD

**Issue by jstillwa** [tkdan235/mediatidy#12]
When issuing the clean command on OSX Sierra, this is the error I'm getting. Tried with different paths, one path, many paths, etc. 

/usr/local/lib/node_modules/mediatidy/node_modules/node-dir/lib/paths.js:124
  var bufdir = Buffer.from(dir);
                      ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.files (/usr/local/lib/node_modules/mediatidy/node_modules/node-dir/lib/paths.js:124:23)
    at /usr/local/lib/node_modules/mediatidy/lib/media.coffee:48:17
    at FSReqWrap.cb [as oncomplete] (fs.js:216:19)

**Comment by jstillwa** [comment]
This was a node version issue.
