### ISSUE TITLE
Error When Running ./mediatidy clean

### ISSUE THREAD

**Issue by dcplaya** [tkdan235/mediatidy#16]
```
/home/temp/mediatidy/node_modules/node-dir/lib/paths.js:124
  var bufdir = Buffer.from(dir);
                      ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.files (/home/temp/mediatidy/node_modules/node-dir/lib/paths.js:124:23)
    at /home/temp/mediatidy/lib/media.coffee:48:17
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
```

**Comment by pdxdoughnut** [comment]
I'm seeing this same problem.

$ mediatidy --version
0.5.0
